name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your feature request! Please describe what you'd like to see.
  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature.
      placeholder: Describe the feature
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem Solved
      description: What problem does this solve?
      placeholder: Describe the problem
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions you've considered.
  - type: checkboxes
    id: checkbox
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues
          required: true
        - label: This is a new feature, not a refactoring request
          required: true
